# Orb 'cypress-io/cypress@1' resolved to 'cypress-io/cypress@1.13.0'
version: 2
jobs:
  cypress/run:
    docker:
    - image: cypress/base:10
    parallelism: 1
    steps:
    - checkout
    - restore_cache:
        keys:
        - cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Check if package-lock.json exists
        command: |
          if [ ! -e ./package-lock.json ]; then
            echo "The Cypress orb uses 'npm ci' to install 'node_modules', which requires a 'package-lock.json'."
            echo "A 'package-lock.json' file was not found. Please run 'npm install' in your project,"
            echo "and commit 'package-lock.json' to your repo."
            exit 1
          fi
        working_directory: ''
    - run:
        name: Npm CI
        command: npm ci
        working_directory: ''
    - run:
        name: Verify Cypress
        command: npx cypress verify
        working_directory: ''
    - save_cache:
        key: cache-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
        - ~/.npm
        - ~/.cache
    - run:
        name: Run Cypress tests
        no_output_timeout: 10m
        command: "npx cypress run \\\n   \\\n   \\\n  "
        working_directory: ''
workflows:
  build:
    jobs:
    - cypress/run
  version: 2

# Original config.yml file:
# # to use orbs, must use version >= 2.1
# version: 2.1
# orbs:
#   # import Cypress orb by specifying an exact version x.y.z
#   # or the latest version 1.x.x using \"@1\" syntax
#   cypress: cypress-io/cypress@1
# workflows:
#   build:
#     jobs:
#       # \"cypress\" is the name of the imported orb
#       # \"run\" is the name of the job defined in Cypress orb
#       - cypress/run:
#           no-workspace: true
